env:
  browser: true
  commonjs: true
  es6: true
plugins:
  - prettier
  - jsdoc
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prettier/prettier: error
extends:
  plugin:jsdoc/recommended
