language: node_js
cache:
  directories:
    - node_modules
matrix:
  include:
    - os: linux
node_js:
  - "12"
  - "14"
  - node
  - lts/*
script: "npm run-script lint && npm run jsdoc && npm run test-pipeline"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
